# Generated by Django 2.0.3 on 2018-04-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('devolucao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Devolucao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbiblioteca.Usuario'),
        ),
    ]
