# Generated by Django 2.0.3 on 2018-04-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbiblioteca', '0002_auto_20180403_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='livros',
            field=models.ManyToManyField(to='adminbiblioteca.Livro'),
        ),
    ]
