# Generated by Django 2.0.3 on 2018-04-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminbiblioteca', '0003_emprestimo_livros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='matricula',
            new_name='usuario',
        ),
    ]
